steps:
- name: 'docker'
  args: ['build', 'centos', '-f', 'centos/Dockerfile.build', '-t', 'builder']
- name: 'builder'
  args: ['/build.sh']
- name: 'docker'
  args: ['build', 'centos', '-t', 'gcr.io/$PROJECT_ID/centos7:latest']
images: ['gcr.io/$PROJECT_ID/centos7:latest']
