dist: trusty
sudo: required
python:
  - "2.7"
os:
  - linux

jdk:
  - oraclejdk8

language: go
go: 1.10.x
install: true

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
install:
  - go get -u github.com/bazelbuild/buildifier/buildifier
  - curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && sudo mv container-diff-linux-amd64 /usr/local/bin/container-diff
  - export PATH=$PATH:$HOME/bin && mkdir -p $HOME/bin
  - wget https://github.com/bazelbuild/buildtools/releases/download/0.11.1/buildifier && chmod +x buildifier && mv buildifier $HOME/bin/
  - wget https://github.com/bazelbuild/bazel/releases/download/0.19.2/bazel-0.19.2-linux-x86_64 && mv bazel-0.19.2-linux-x86_64 bazel && chmod +x bazel && mv bazel $HOME/bin/

script:
- ./test.sh
©

script:
 - make test
