steps:
        - name: gcr.io/sharif-test/docker-mkdebootstrap:jessie
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=gcr.io/sharif-test/debian:2016-09-06'
                - '.'
images: ['gcr.io/sharif-test/debian:2016-09-06']
