# All items surrounded by %% are variables to be replaced with real values.
# %REPO%: The repository to push debian to, e.g. gcr.io/myproject
# %TAG%: What the tag the image with, e.g. latest
# %VERSION%: The version of debian to build, e.g. jessie
# %NUM%: The version number associated with the %VERSION% string, e.g. 8 for jessie
steps:
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=%REPO%/mkdebootstrap:%VERSION%'
                - 'mkdebootstrap/'
        - name: %REPO%/mkdebootstrap:%VERSION%
          args:
                - '-d'
                - '/workspace'
                - 'debootstrap'
                - '--variant=minbase'
                - '%VERSION%'
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=%REPO%/debian%NUM%:%TAG%'
                - '.'
images: ['%REPO%/mkdebootstrap:%VERSION%', '%REPO%/debian%NUM%:%TAG%']
