steps:
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=%REPO%/mkdebootstrap:%VERSION%'
                - 'mkdebootstrap/'
        - name: %REPO%/mkdebootstrap:%VERSION%
          args:
                - '-d'
                - '/workspace'
                - 'debootstrap'
                - '--variant=minbase'
                - '%VERSION%'
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=%REPO%/debian%NUM%:%TAG%'
                - '.'
images: ['%REPO%/mkdebootstrap:%VERSION%', '%REPO%/debian%NUM%:%TAG%']
