steps:
        - name: $REPO$/docker-mkdebootstrap:jessie
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=$REPO$/debian:$TAG$'
                - '.'
images: ['$REPO$/debian:$TAG$']
