steps:
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=%REPO%/mkdebootstrap:%VERSION%'
                - 'mkdebootstrap/'
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=docker-mkdebootstrap'
                - 'docker-mkdebootstrap'
        # This is an intermediate step in order to run docker in privileged mode.
        # It just pulls the mkdebootstrap image built just above and runs
        # debootstrap on it.
        - name: docker-mkdebootstrap
          args:
                - '%REPO%'
                - '%VERSION%'
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=%REPO%/debian:%TAG%'
                - '.'
images: ['%REPO%/mkdebootstrap:%VERSION%', '%REPO%/debian:%TAG%']
